<package format="3">
	<name>tobas_voliro_like_description</name>
	<version>0.0.0</version>
	<description>A UADF example for an active tilt hexacopter.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>MIT</license>
	<buildtool_depend>ament_cmake</buildtool_depend>
	<export>
		<build_type>ament_cmake</build_type>
	</export>
</package>
